os: linux
dist: xenial
language: node_js
node_js:
  - 10
  - 12
  - 14
services:
  - docker
before_script:
  - docker compose up -d redis1 redis2 redis3
  - docker compose run waiter
after_success: 'npm run coveralls'
cache: yarn
jobs:
  fast_finish: true
