name: CI (push)

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  intergartion-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    env:
      COVERALLS_REPO_TOKEN: '${{ secrets.COVERALLS_REPO_TOKEN }}'
      COVERALLS_GIT_BRANCH: '${{ github.ref }}'

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - uses: c-hive/gha-yarn-cache@v1

      - run: yarn --frozen-lockfile

      - run: docker compose up -d redis1 redis2 redis3
      - run: docker compose run waiter

      - run: yarn test-ci-with-coverage
