name: CI (push)

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  integration-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    env:
      COVERALLS_REPO_TOKEN: '${{ secrets.COVERALLS_REPO_TOKEN }}'
      COVERALLS_GIT_BRANCH: '${{ github.ref }}'

    steps:
      - uses: actions/checkout@v4
      - name: Enable Corepack
        run: corepack enable

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - run: yarn install --immutable

      - run: docker compose up -d redis1 redis2 redis3
      - run: docker compose run waiter

      - run: yarn test-ci-with-coverage
