name: CI (PR)

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  integration-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x, 20.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - run: yarn --frozen-lockfile

      - run: docker compose up -d redis1 redis2 redis3
      - run: docker compose run waiter

      - run: yarn test
