name: CI (PR)

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  integration-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - uses: actions/checkout@v4
      - name: Enable Corepack
        run: corepack enable

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - run: yarn install --immutable

      - run: docker compose up -d redis1 redis2 redis3
      - run: docker compose run waiter

      - run: yarn build
      - run: yarn lint
      - run: yarn test
